exports.handler = async (event) => {
    const CONTENT = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="UTF-8">
      <title>Static HTML from Lambda</title>
  </head>
  <body>
      <h1>Hello from Business One!</h1>
      <p>This is a static HTML page generated by a Lambda function.</p>
  </body>
  </html>
  `;
  
    const response = {
      statusCode: 200,
      headers: {
        'Content-Type': 'text/html',
      },
      body: CONTENT,
    };
  
    return response;
  };
  